# Phone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phone-deployment
  namespace: phone-app
  labels:
    app: phone
spec:
  # imagePullSecrets:
  #   - name: ecr-secret
  replicas: 1
  selector:
    matchLabels:
      app: phone
  template:
    metadata:
      labels:
        app: phone
    spec:
      containers:
        - name: phone
          image: devopseasylearning/s9-s8:20250629-192610-49a3090
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: phone-nodeport-service
  namespace: phone-app
  labels:
    app: phone
spec:
  type: NodePort
  selector:
    app: phone
  ports:
    - port: 80
      targetPort: 8080