apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s9-s8
  namespace: argocd-s6arsene
spec:
  project: s9-s8
  source:
    repoURL: "https://github.com/DEL-ORG/del-student-devops-argocd.git"
    targetRevision: main
    path: deployment
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - ApplyOutOfSyncOnly=true
      - ManualSync=fase